"""
Central enumerations for the AI Client Follow-Up & CRM Automation System.

These enums are the single source of truth for client stages, tones,
priorities, and statuses used throughout the deterministic business logic
(follow-up engine, next-action engine, template engine) and the ORM models.
"""

from enum import Enum


class ClientStage(str, Enum):
    NEW_LEAD = "NEW_LEAD"
    INITIAL_FOLLOW_UP = "INITIAL_FOLLOW_UP"
    FOLLOW_UP_2 = "FOLLOW_UP_2"
    FOLLOW_UP_3 = "FOLLOW_UP_3"
    PARTICIPATION_PENDING = "PARTICIPATION_PENDING"
    INTERESTED = "INTERESTED"
    MEETING_REQUESTED = "MEETING_REQUESTED"
    MEETING_SCHEDULED = "MEETING_SCHEDULED"
    MEETING_CONFIRMED = "MEETING_CONFIRMED"
    MEETING_COMPLETED = "MEETING_COMPLETED"
    AGREEMENT_SENT = "AGREEMENT_SENT"
    AGREEMENT_OPENED = "AGREEMENT_OPENED"
    AGREEMENT_PENDING_SIGNATURE = "AGREEMENT_PENDING_SIGNATURE"
    AGREEMENT_CALL_REQUIRED = "AGREEMENT_CALL_REQUIRED"
    AGREEMENT_FINAL_FOLLOW_UP = "AGREEMENT_FINAL_FOLLOW_UP"
    SIGNED = "SIGNED"
    DECLINED = "DECLINED"
    BUDGET_OBJECTION = "BUDGET_OBJECTION"
    SPECIAL_OFFER = "SPECIAL_OFFER"
    PAYMENT_DISCUSSION = "PAYMENT_DISCUSSION"
    VIRTUAL_PARTICIPATION = "VIRTUAL_PARTICIPATION"
    COMPLETED = "COMPLETED"
    DO_NOT_CONTACT = "DO_NOT_CONTACT"


# Terminal stages: the follow-up engine must never recommend a normal
# follow-up action once a client is in one of these.
TERMINAL_STAGES = {
    ClientStage.DECLINED,
    ClientStage.SIGNED,
    ClientStage.COMPLETED,
    ClientStage.DO_NOT_CONTACT,
}


class Tone(str, Enum):
    POLITE_PROFESSIONAL = "POLITE_PROFESSIONAL"
    FRIENDLY_ENGAGING = "FRIENDLY_ENGAGING"
    ACTION_ORIENTED = "ACTION_ORIENTED"
    SUBTLE_URGENCY = "SUBTLE_URGENCY"
    EXECUTIVE_FRIENDLY = "EXECUTIVE_FRIENDLY"


class Priority(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class AgreementStatus(str, Enum):
    NOT_SENT = "NOT_SENT"
    SENT = "SENT"
    OPENED = "OPENED"
    PENDING_SIGNATURE = "PENDING_SIGNATURE"
    SIGNED = "SIGNED"
    DECLINED = "DECLINED"


class MeetingStatus(str, Enum):
    REQUESTED = "REQUESTED"
    SCHEDULED = "SCHEDULED"
    CONFIRMED = "CONFIRMED"
    RESCHEDULED = "RESCHEDULED"
    COMPLETED = "COMPLETED"
    MISSED = "MISSED"
    CANCELLED = "CANCELLED"


class EmailDirection(str, Enum):
    OUTBOUND = "OUTBOUND"
    INBOUND = "INBOUND"


class EmailStatus(str, Enum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    FAILED = "FAILED"
    MOCK_SENT = "MOCK_SENT"
    REPLY_REQUIRED = "REPLY_REQUIRED"
    REPLIED = "REPLIED"


class TemplateCategory(str, Enum):
    FOLLOW_UP_1 = "FOLLOW_UP_1"
    FOLLOW_UP_2 = "FOLLOW_UP_2"
    FOLLOW_UP_3 = "FOLLOW_UP_3"
    PARTICIPATION_CONFIRMATION = "PARTICIPATION_CONFIRMATION"
    MEETING_CONFIRMATION = "MEETING_CONFIRMATION"
    MEETING_REMINDER = "MEETING_REMINDER"
    MEETING_RESCHEDULE = "MEETING_RESCHEDULE"
    CALL_ATTEMPT = "CALL_ATTEMPT"
    MANAGER_ID = "MANAGER_ID"
    AGREEMENT_SENT = "AGREEMENT_SENT"
    AGREEMENT_REMINDER = "AGREEMENT_REMINDER"
    AGREEMENT_OPEN = "AGREEMENT_OPEN"
    AGREEMENT_CALL = "AGREEMENT_CALL"
    AGREEMENT_FINAL = "AGREEMENT_FINAL"
    DECLINED = "DECLINED"
    BUDGET_OBJECTION = "BUDGET_OBJECTION"
    SPECIAL_OFFER = "SPECIAL_OFFER"
    PAYMENT_DISCUSSION = "PAYMENT_DISCUSSION"
    VIRTUAL_PARTICIPATION = "VIRTUAL_PARTICIPATION"
    TITLE_SUGGESTION = "TITLE_SUGGESTION"
    IMAGE_REQUEST = "IMAGE_REQUEST"
    OTHER_APPROVED_TEMPLATE = "OTHER_APPROVED_TEMPLATE"


class ResponseClassification(str, Enum):
    INTERESTED = "INTERESTED"
    NOT_INTERESTED = "NOT_INTERESTED"
    NEEDS_MORE_INFORMATION = "NEEDS_MORE_INFORMATION"
    BUDGET_CONCERN = "BUDGET_CONCERN"
    NEEDS_TIME = "NEEDS_TIME"
    MEETING_REQUEST = "MEETING_REQUEST"
    AGREEMENT_QUESTION = "AGREEMENT_QUESTION"
    READY_TO_SIGN = "READY_TO_SIGN"
    DECLINED = "DECLINED"
    NO_RESPONSE = "NO_RESPONSE"
    OTHER = "OTHER"
